name: .NET Core

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - dev

env:
  TargetNet9: True
  TargetNet8: True

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true
    name: Wilson GitHub Action Test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
    - name: Setup .NET 9.0.x
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 9.0.100-rc.2.24474.11

    - name: Run the tests
      run: dotnet test Wilson.sln --collect:"XPlat Code Coverage" --settings:./build/CodeCoverage.runsettings

    - name: Create code coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:CodeCoverage -reporttypes:'MarkdownSummaryGithub;Cobertura'

    - name: Write Coverage to Job Summary
      shell: bash
      run: |
        cat CodeCoverage/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
        echo "COMMENT_CONTENT_ENV_VAR<<EOF" >> $GITHUB_ENV
        echo $(cat CodeCoverage/SummaryGithub.md) >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Comment Coverage in PR
      uses: actions/github-script@v7
      id: comment
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.COMMENT_CONTENT_ENV_VAR
          })

    # Run baseline package validation
    - name: Pack
      run: dotnet pack Product.proj --no-restore --no-build